# Generated by Django 5.1.2 on 2024-10-25 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('ipo_name', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('issue_size', models.IntegerField()),
                ('issue_price', models.IntegerField()),
                ('qib', models.FloatField()),
                ('hni', models.FloatField()),
                ('rii', models.FloatField()),
                ('age', models.IntegerField()),
                ('predicted_opening', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
                ('context', models.ManyToManyField(blank=True, related_name='chats', to='chat.ipo')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('content_html', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.ipo')),
            ],
        ),
    ]
