# Generated by Django 5.1.2 on 2024-10-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='context',
        ),
        migrations.AddField(
            model_name='message',
            name='context',
            field=models.ManyToManyField(blank=True, related_name='messages', to='chat.ipo'),
        ),
    ]
