# Generated by Django 5.1.2 on 2024-10-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_remove_message_context_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='context',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='context',
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='message',
            name='context',
            field=models.TextField(default='m'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IPO',
        ),
    ]
